server:
  port: 8081
spring:
  application:
    name: fegin-provider
  cloud:
    # Nacos \u4F5C\u4E3A\u6CE8\u518C\u4E2D\u5FC3\u7684\u914D\u7F6E\u9879
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    # Sentinel \u914D\u7F6E\u9879\uFF0C\u5BF9\u5E94 SentinelProperties \u914D\u7F6E\u5C5E\u6027\u7C7B
#    sentinel:
#      enabled: true # \u662F\u5426\u5F00\u542F\u3002\u9ED8\u8BA4\u4E3A true \u5F00\u542F
#      transport:
#        dashboard: 127.0.0.1:8084 # Sentinel \u63A7\u5236\u53F0\u5730\u5740