spring:
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: a15b5ade-277e-42a0-a9d5-88b9cea6fc98 # Nacos 命名空间 dev 的编号
